export const projects = [
  {
    title: 'Autonomous Car with PID',
    description: "Developed an autonomous car with Ackerman steering to navigate a square path using a PID controller for precision. Integrated sensors (PixyCam, MPU gyroscope, and encoder) for real-time adjustments and ESP32 for mobile data monitoring. Contributed 100% to the electronics, designing and manufacturing a custom PCB in KiCad, and completing all wiring and connections. Also led the mechanical design in SolidWorks and control calibration in MATLAB/Simulink.",
    image: '/images/Carrito Autónomo.jpeg',
    tags: ['Control system', 'PCB', 'Hardware','Arduino'],
    source: 'https://www.youtube.com/watch?v=7SYkyt2u-o4',
    visit: '/Reportes/Reporte_RobotAutónomo.pdf',
    id: 0,
  },
  {
    title: 'Automated Cell ABB',
    description: "Proposed a fully autonomous robotic cell for laser welding, designed to eliminate human intervention. Created fixtures for conveyor-based part placement and a dual gripper to streamline piece transport, improving speed and efficiency. Utilized RobotStudio for movement programming and simulation, and SolidWorks for cell, fixture, and gripper design.",
    image: '/images/CeldaABB.png',
    tags: ['Robotics', 'Tooling', 'RobotStudio'],
    source: 'https://youtu.be/tIWlGmzbWMk',
    visit: '/Reportes/Reporte_ABB.pdf',
    id: 1,
  },
  {
    title: 'Automated Cell Parker',
    description: "Developed a semi-automated cell for Parker’s valve assembly process, integrating robots and feeders to automate inlet/outlet placement and valve transport between presses and ovens. Used SolidWorks for fixture and gripper design, Tecnomatix for robotic simulation, and PlantSimulation to analyze process efficiency. Project earned recognition for its promising impact on production.",
    image: '/images/CeldaParker.png',
    tags: ['Tecnomatix', 'Plant Simulation', 'Optimization'],
    source: 'https://youtu.be/JbNbvazud5s',
    visit: '/Reportes/Reporte_Parker.pdf',
    id: 2,
  },
  {
    title: 'Gripper for RoBorregos',
    description: "Designed a dual-arm gripper for the RoBorregos robot, used in the TMR competition in Veracruz. Integrated servomotors with an embedded microcontroller for precise control, and redesigned the gripper body to accommodate voltage regulation components. Developed a modular coupler for versatile positioning on the XArm.",
    image: '/images/GripperRoBorregos.jpeg',
    tags: ['Robotics', 'Hardware', 'Solidworks', 'Embedded'],
    source: 'https://youtube.com/shorts/x3SOOY1XLag',
    visit: '#',
    id: 3,
  },
  {
    title: 'Electric Motor',
    description: "Built a custom brush electric motor to explore electromagnetic fields and motor mechanics. Designed with dual square coils, 3D-printed supports, and an improvised aluminum commutator, powered by 4A for optimal performance. Won 1st place in a class competition. ",
    image: '/images/electricMotor.jpg',
    tags: ['SolidWorks', 'Electromagnetism', 'Electrical'],
    source: 'https://youtube.com/shorts/KNSfH3USeRM',
    visit: '/Reportes/MotorEléctrico_Geminis.pdf',
    id: 4,
  },
  {
    title: 'John Deere Fixture',
    description: "Designed a clamp for John Deere to solve production issues with steel plowshares. The original process involved bending a steel plate into a crescent shape, but fixed hydraulic clamps caused it to deform into an omega shape instead of the desired semicircular form. My solution provided a degree of freedom while ensuring safety, effectively resolving the problem.",
    image: '/images/johnDeereFixtureProject.jpg',
    tags: ['SolidWorks', 'GD&T','Manufacturing', 'Metallurgy'],
    source: '#',
    visit: '/Reportes/JohnDeereFixture.pdf',
    id: 5,
  },
  {
    title: 'TMR Competition',
    description: "Competed in the TMR competition in Xalapa, Veracruz, as the mechanical lead for RoBorregos. Oversaw full assembly and maintenance of the robot, including gripper setup and real-time redesigns for structural adjustments. Collaborated with programmers by reconfiguring supports for optimal vision calibration and troubleshooting.",
    image: '/images/TMR_XALAPA.jpg',
    tags: ['Leadership', 'Mechanical design','3D print'],
    source: 'https://youtu.be/F3AE-Iep8ME',
    visit: '#',
    id: 6,
  },
  {
    title: 'Automated Goalkeeper Game Project',
    description: "Developed a mechanical goalkeeper for a four-player soccer-inspired game. Designed a belt-driven mechanism powered by a high-speed Pololu motor to move the goalkeeper along the board, along with an internal solenoid mechanism for ball striking. Assisted with Arduino programming and created a custom PCB with circuitry to eliminate parasitic currents from the solenoid and motor, protecting all other components. ",
    image: '/images/RetoGuardameta.jpeg',
    tags: ['Arduino', 'Mechanical design','Hardware'],
    source: 'https://www.youtube.com/playlist?list=PLKIdz1Vre8es1eA7vWQT0aJ8QZ8ZLUJHN',
    visit: '/Reportes/Reto_guardameta.pdf',
    id: 7,
  },
  {
    title: 'Temperature Control System',
    description: "Developed a prototype refrigerator with real-time temperature monitoring using OpAmps and Arduino. Designed a custom circuit as an Arduino shield to convert mV readings from an LM35 temperature sensor to volts, using a multiplier circuit and wire-wrap technique for durability. Data was displayed and graphed in Excel for real-time temperature tracking.",
    image: '/images/ControlTemp.jpeg',
    tags: ['Arduino', 'OpAmps','Thermodynamics','Hardware'],
    source: 'https://youtube.com/shorts/wskB3M_mNlk?feature=share',
    visit: '/Reportes/ControlTemperatura.pdf',
    id: 8,
  },
  {
    title: 'Renewable Energy Diploma',
    description: "Completed an intensive course on solar energy focused on residential solar panel installation. Gained skills in calculating panel requirements based on household consumption, determining optimal panel angles, and connecting panels to inverters for home energy use. Covered regulatory requirements in Mexico and learned to build solar water heaters to reduce energy costs.",
    image: '/images/Solenium.jpg',
    tags: ['Solar energy', 'Electrical','Energy efficency'],
    source: '#',
    visit: '/Reportes/Reconocmiento_Solar.pdf',
    id: 9,
  },
];

export const TimeLineData = [
  { year: 2016, text: 'Started my journey as a developer.', },
  { year: 2017, text: 'Worked intensively on ROMs & Kernels.', },
  { year: 2018, text: 'Learned Android app development.', },
  { year: 2019, text: 'Finished Diploma in Computer Engineering.', },
  { year: 2020, text: 'Aquired new skills while trying not to catch COVID-19', },
  { year: 2021, text: 'Survived COVID-19 and got my first Job at Primebook.', },
  { year: 2022, text: 'Completed B.Tech in Information Technology.', },
  { year: 2023, text: 'Year under progress....', },
];